CREATE TABLE IF NOT EXISTS AUTHORS (AUTHOR_ID BIGINT PRIMARY KEY, name VARCHAR(255));
CREATE TABLE IF NOT EXISTS GENRES(GENRE_ID BIGINT PRIMARY KEY, name VARCHAR(255));
CREATE TABLE IF NOT EXISTS BOOKS(BOOK_ID BIGINT PRIMARY KEY, name VARCHAR(255),
                                 AUTHOR_ID BIGINT , GENRE_ID BIGINT ,
                   FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID),
                   FOREIGN KEY (GENRE_ID) REFERENCES GENRES(GENRE_ID));